import { describe, it, expect } from 'vitest';
import { Project } from 'ts-morph';
import { FactExtractor } from '../../src/parser/fact-extractor.js';
import { KnowledgeBase } from '../../src/kb/knowledge-base.js';

describe('Phase -1: Analyze FactSet Structure for Confidence Scoring', () => {
  it('should inspect actual Phase 2 fact structure', () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const extractor = new FactExtractor();
    const kb = new KnowledgeBase();

    // Create file with various documentation levels
    const sourceFile = project.createSourceFile(
      'src/app.ts',
      `
      /** Well-documented function with params and return */
      export function welldocumented(x: number): string {
        return 'test';
      }

      function undocumented() {
        return 'test';
      }

      export class MyClass {
        /** Documented method */
        method(a: string): void {}

        undocumentedMethod() {}
      }

      export const MY_CONSTANT = 42;
      `
    );

    const result = extractor.extract(sourceFile, 'src/app.ts');
    result.entities.forEach(e => kb.insertEntity(e));
    result.relations.forEach(r => kb.insertRelation(r));
    result.factSets.forEach(fs => kb.insertFactSet(fs));

    // Get all factSets and inspect structure
    const factSets = kb.getAllFactSets();
    console.log('\n=== FACT SET STRUCTURE ===');
    console.log('Number of fact sets:', factSets.length);

    if (factSets.length > 0) {
      const sampleFactSet = factSets[0];
      console.log('Sample FactSet:', {
        id: sampleFactSet.id,
        factsCount: sampleFactSet.facts.length,
        evidenceScore: sampleFactSet.evidenceScore,
        hasEntityIdField: 'entityId' in sampleFactSet  // Should be false
      });

      console.log('\n=== FACTS STRUCTURE ===');
      sampleFactSet.facts.forEach((fact, i) => {
        console.log(`Fact ${i}:`, {
          subjectId: fact.subjectId.substring(0, 20) + '...',
          predicate: fact.predicate,
          object: fact.object,
          objectType: typeof fact.object
        });
      });
    }

    // Collect all predicates Phase 2 generates
    const allPredicates = new Set<string>();
    factSets.forEach(fs => {
      fs.facts.forEach(f => allPredicates.add(f.predicate));
    });
    console.log('\n=== ALL PREDICATES GENERATED BY PHASE 2 ===');
    console.log(Array.from(allPredicates).sort());

    // Check what's on entities (not facts)
    const entities = kb.getAllEntities();
    console.log('\n=== ENTITY STRUCTURE (NOT FACTS) ===');
    entities.forEach(e => {
      console.log(`Entity ${e.kind} "${e.name}":`, {
        exported: e.exported,
        hasSignature: !!e.signature,
        sideEffects: e.attributes?.sideEffects,
        errors: e.attributes?.errors
      });
    });

    // Validate assumptions
    expect(factSets.length).toBeGreaterThan(0);
    factSets.forEach(fs => {
      // ✅ facts is an array
      expect(Array.isArray(fs.facts)).toBe(true);

      // ✅ sources defined
      expect(fs.sources).toBeDefined();

      // ✅ NO entityId field on FactSet
      expect('entityId' in fs).toBe(false);

      // ✅ Each fact has subjectId
      fs.facts.forEach(fact => {
        expect(fact.subjectId).toBeDefined();
        expect(typeof fact.subjectId).toBe('string');
      });
    });

    // Validate available predicates
    expect(allPredicates.has('is-function')).toBe(true);
    expect(allPredicates.has('has-signature')).toBe(true);
    expect(allPredicates.has('has-jsdoc')).toBe(true);

    // Validate MISSING predicates (confirm they don't exist)
    expect(allPredicates.has('is-exported')).toBe(false);  // It's on entity!
    expect(allPredicates.has('has-test-coverage')).toBe(false);
    expect(allPredicates.has('has-jsdoc-params')).toBe(false);
    expect(allPredicates.has('has-jsdoc-returns')).toBe(false);
    expect(allPredicates.has('dynamic-pattern-warning')).toBe(false);
    expect(allPredicates.has('has-comment')).toBe(false);

    // Validate entity fields (NOT facts)
    const exportedFunc = entities.find(e => e.name === 'welldocumented');
    expect(exportedFunc?.exported).toBe(true);  // Boolean on entity
    expect(exportedFunc?.signature).toBeDefined();  // String on entity
  });
});
